#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BATCH_LENGTH 99
#define NORMALIZED_RANGE_MIN -10
#define NORMALIZED_RANGE_MAX 10
#define NORMALIZATION_RANGE 20
#define LOWER_FREQUENCY_THRESHOLD 8
#define UPPER_FREQUENCY_THRESHOLD 14

#endif
