#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BATCH_LENGTH 99
#define LOWER_THRESHOLD_INTERSECTIONS 8
#define UPPER_THRESHOLD_INTERSECTIONS 14

#define LOWER_THRESHOLD_BPM 50
#define UPPER_THRESHOLD_BPM 80

#define NORMALIZED_INPUT_DURATION 10
#define NORMALIZED_INPUT_BATCH_EXIT_CODE 99
#define NORMALIZED_INPUT_LOWER_BOUND -10
#define NORMALIZED_INPUT_UPPER_BOUND 10

#endif
