#ifndef CONSTANTS_H
#define CONSTANTS_H

#ifndef BATCH_LENGTH
#define BATCH_LENGTH 99
#endif

#define LOWER_FREQUENCY_THRESHOLD 8
#define UPPER_FREQUENCY_THRESHOLD 14
#define NORMALIZED_INPUT_DURATION 10

#define LOWER_VALUE_THRESHOLD -10
#define UPPER_VALUE_THRESHOLD 10

#define EXIT_CODE 99

#endif
